version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      semantic-release:
        patterns:
          - "@semantic-release/exec"
          - "semantic-release"
      jest:
        patterns:
          - "@types/jest"
          - "jest"
          - "jest-junit"
          - "ts-jest"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "@trivago/prettier-plugin-sort-imports"
