name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: npm

    - name: yarn install, build and test
      run: |
        yarn install
        yarn run test
        yarn run build
